# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR C:\Users\User

# Copy the Python script into the container
COPY calci.py .

# Define the default command to run the script
ENTRYPOINT ["python", "calci.py"]
